package model.am.client;

import java.sql.Date;

import model.am.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 29 23:10:27 PKT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }

    public void closeHeader(int programId, Date closingDate) {
        Object _ret =
            this.riInvokeExportedMethod(this,"closeHeader",new String [] {"int","java.sql.Date"},new Object[] {new Integer(programId), closingDate});
        return;
    }
}
