package model.am.common;

import java.sql.Date;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 29 23:10:27 PKT 2014
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void closeHeader(int programId, Date closingDate);
}
